name: List Accessible Repositories

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  list-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositories
      run: |
        mkdir repos
        git init --bare repos/checkout.git
        git --git-dir=repos/checkout.git remote add origin https://github.com/${{ github.repository_owner }}/${{ github.repository }}
        git --git-dir=repos/checkout.git fetch --prune
        git --git-dir=repos/checkout.git config --get-regexp 'remote\..*\.url' | sed 's/^remote\.\(.*\)\.url /:\1 /' > repos.txt
        echo "List of accessible repositories:"
        cat repos.txt
        
    - name: Upload repo list
      uses: actions/upload-artifact@v3
      with:
        name: repo-list
        path: repos.txt
