name: List Accessible Repositories

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  list-repos:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositories
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git init --bare repos
        git --git-dir=repos remote add origin https://github.com/${{ github.repository_owner }}/${{ github.repository }}
        git --git-dir=repos fetch --prune --all
        git --git-dir=repos remote -v > repos.txt
        echo "List of accessible repositories:"
        cat repos.txt
        
    - name: Upload repo list
      uses: actions/upload-artifact@v3
      with:
        name: repo-list
        path: repos.txt
