name: Manage Workflow Runs

on:
  workflow_dispatch:
    inputs:
      FUNCTION:
        description: "Which function should I perform?"
        required: true
        default: "delete failed"
        type: choice
        options:
          - "run"
          - "list all"
          - "list failed"
          - "delete all"
          - "delete failed"
      OWNER:
        description: "Owner"
        required: true
        type: string
        default: "BillReyor"
      REPOSITORY:
        description: "Repository"
        required: true
        type: string
        default: "Root-Bot"
      WORKFLOW_NAME:
        description: "Workflow, if not specified all workflows will be used."
        required: false
        type: string

jobs:
  Get_Workflow_IDs:
    name: Get Workflow IDs
    runs-on: ubuntu-22.04
    outputs:
      workflow_ids: ${{ steps.get_ids.outputs.workflow_ids }}
    steps:
      - name: Get Workflow IDs
        id: get_ids
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mapfile -t WORKFLOW_IDs < <(gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows | jq '.workflows[] | select(.name=="${{ inputs.WORKFLOW_NAME }}" // true) | .id')
          echo "${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}: ${{ inputs.WORKFLOW_NAME }}"
          echo "::set-output name=workflow_ids::$(printf '%s,' "${WORKFLOW_IDs[@]}")"

  Run:
    name: Run Workflow
    needs: Get_Workflow_IDs
    if: ${{ github.event.inputs.FUNCTION == 'run' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Run Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra WORKFLOW_IDS <<< "${{ needs.Get_Workflow_IDs.outputs.workflow_ids }}"
          for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/dispatches \
              -d '{"ref":"dev"}'
          done

  List_All:
    name: List All Workflow Runs
    needs: Get_Workflow_IDs
    if: ${{ github.event.inputs.FUNCTION == 'list all' }}
    runs-on: ubuntu-22.04
    steps:
      - name: List All Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra WORKFLOW_IDS <<< "${{ needs.Get_Workflow_IDs.outputs.workflow_ids }}"
          for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | .id'
          done

  List_Failed:
    name: List Failed Workflow Runs
    needs: Get_Workflow_IDs
    if: ${{ github.event.inputs.FUNCTION == 'list failed' }}
    runs-on: ubuntu-22.04
    steps:
      - name: List Failed Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra WORKFLOW_IDS <<< "${{ needs.Get_Workflow_IDs.outputs.workflow_ids }}"
          for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id'
          done

  Delete_All:
    name: Delete All Workflow Runs
    needs: Get_Workflow_IDs
    if: ${{ github.event.inputs.FUNCTION == 'delete all' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Delete All Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra WORKFLOW_IDS <<< "${{ needs.Get_Workflow_IDs.outputs.workflow_ids }}"
          for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done

  Delete_Failed:
    name: Delete Failed Workflow Runs
    needs: Get_Workflow_IDs
    if: ${{ github.event.inputs.FUNCTION == 'delete failed' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Delete Failed Workflow Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra WORKFLOW_IDS <<< "${{ needs.Get_Workflow_IDs.outputs.workflow_ids }}"
          for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"; do
            echo "Workflow ID: $WORKFLOW_ID"
            gh api -X GET /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/workflows/"$WORKFLOW_ID"/runs --paginate | jq '.workflow_runs[] | select(.conclusion=="failure") | .id' | xargs -I{} gh api -X DELETE /repos/${{ inputs.OWNER }}/${{ inputs.REPOSITORY }}/actions/runs/{} --silent
          done
