name: Get Viewer Details

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-viewer-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get available secrets
      id: get-secrets
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        if [ -n "$GH_TOKEN" ]; then
          echo "Using GH_TOKEN"
          echo "token=$GH_TOKEN" >> $GITHUB_OUTPUT
        else
          echo "No repository or organization secrets found"
          echo "Using default GITHUB_TOKEN"
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
        fi
      
    - name: Get viewer details
      env:
        GITHUB_TOKEN: ${{ steps.get-secrets.outputs.token }}
      run: |
        echo "Viewer details:"
        gh api graphql --paginate --field query='
          query {
            viewer {
              login
              name
              email
              company
              location
              avatarUrl
              websiteUrl
              bio
              isBountyHunter
              isEmployee
              isDeveloperProgramMember
              organizations(first: 100) {
                nodes {
                  name
                  description
                  avatarUrl
                  membersWithRole {
                    totalCount
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
              repositories(first: 100) {
                nodes {
                  nameWithOwner
                  description
                  isPrivate
                  isFork
                  isArchived
                  isDisabled
                  isTemplate
                  viewerPermission
                  viewerSubscription
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
              starredRepositories {
                totalCount
              }
              watching {
                totalCount
              }
              followers {
                totalCount
              }
              following {
                totalCount
              }
            }
          }
        ' --jq '.data.viewer'
