name: Get Viewer Details

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-viewer-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get viewer details
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Viewer details:"
        gh api graphql --paginate --field query='
          query {
            viewer {
              login
              name
              email
              company
              location
              avatarUrl
              websiteUrl
              bio
              isBountyHunter
              isEmployee
              isDeveloperProgramMember
              viewerCanChangePinnedRepositories
              viewerCanCreateRepositories
              viewerCanCreatePublicRepositories
              viewerCanCreatePrivateRepositories
              viewerCanCreateOrganizations
              viewerCanViewSamlIdpMetadata
              viewerHovercardContext {
                message
                octicon
              }
              organizations {
                nodes {
                  name
                  description
                  avatarUrl
                  membersWithRole {
                    totalCount
                  }
                }
              }
              repositories {
                nodes {
                  nameWithOwner
                  description
                  isPrivate
                  isFork
                  isArchived
                  isDisabled
                  isTemplate
                  viewerPermission
                  viewerSubscription
                }
              }
              starredRepositories {
                totalCount
              }
              watching {
                totalCount
              }
              followers {
                totalCount
              }
              following {
                totalCount
              }
            }
          }
        ' --jq '.data.viewer'
