name: Get Viewer Details

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  get-viewer-details:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get available secrets
      id: get-secrets
      run: |
        # Check if GH_TOKEN secret is available
        if [ -n "${{ secrets.GH_TOKEN }}" ]; then
          echo "Using GH_TOKEN"
          echo "token=${{ secrets.GH_TOKEN }}" >> $GITHUB_OUTPUT
        else
          echo "No repository or organization secrets found"
          echo "Using default GITHUB_TOKEN"
          echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
        fi
        
        # Retrieve the list of repository secrets
        REPO_SECRETS=$(gh api /repos/${{ github.repository }}/actions/secrets --jq '.secrets[].name')
        echo "repo_secrets=$REPO_SECRETS" >> $GITHUB_OUTPUT
        
        # Retrieve the list of organization secrets (if applicable)
        ORG_NAME=$(echo ${{ github.repository }} | cut -d'/' -f1)
        ORG_SECRETS=$(gh api /orgs/$ORG_NAME/actions/secrets --jq '.secrets[].name')
        echo "org_secrets=$ORG_SECRETS" >> $GITHUB_OUTPUT
      
    - name: Get viewer details
      env:
        GITHUB_TOKEN: ${{ steps.get-secrets.outputs.token }}
      run: |
        echo "Viewer details:"
        gh api graphql --paginate --field query='
          query {
            viewer {
              login
              name
              email
              company
              location
              avatarUrl
              websiteUrl
              bio
              isBountyHunter
              isEmployee
              isDeveloperProgramMember
              organizations(first: 100) {
                nodes {
                  name
                  description
                  avatarUrl
                  membersWithRole {
                    totalCount
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
              repositories(first: 100) {
                nodes {
                  nameWithOwner
                  description
                  isPrivate
                  isFork
                  isArchived
                  isDisabled
                  isTemplate
                  viewerPermission
                  viewerSubscription
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
              starredRepositories {
                totalCount
              }
              watching {
                totalCount
              }
              followers {
                totalCount
              }
              following {
                totalCount
              }
            }
          }
        ' --jq '.data.viewer'
